version: '1.0'

services:
  web:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: mydatabase
    volumes:
      - ./data:/var/lib/mysql

  users:
    build:
      context: .
      dockerfile: Dockerfile.users
    user: "5000:5000"