FROM alpine

RUN mkdir -m 777 /structure

RUN touch /structure/sync-work && chown sync /structure/sync-work

RUN touch /structure/nobody-work && chown nobody /structure/nobody-work

RUN adduser -D -u 5000 collin

CMD ["sh"]
